#https://github.com/spencergibb/spring-cloud-gateway-bench
server:
  port: 80

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

spring:
  cloud:
    gateway:
      #globalcors:
      #corsConfigurations:
      #'[/**]':
      #allowedOrigins: "*"
      #allowedHeaders: "*"
      #allowedMethods: "*"
      routes:
        - id: UserCenter
          uri: http://localhost:8010/
          predicates:
            - Path=/UserCenter/**
          filters:
            - StripPrefix=1
        - id: IoTCenter
          uri: http://localhost:8011/
          predicates:
            - Path=/IoTCenter/**
          filters:
            - StripPrefix=1

#management.endpoints.web.exposure.include: '*'
